export const industryOptions = [
  {
    value: "Information Technology and Services",
    label: "Information Technology and Services",
  },
  { value: "Automotive", label: "Automotive" },
  { value: "Apparel", label: "Apparel" },
  {
    value: "Banking and Financial Services",
    label: "Banking and Financial Services",
  },
  { value: "Biotechnology", label: "Biotechnology" },
  { value: "Chemicals", label: "Chemicals" },
  { value: "Communications", label: "Communications" },
  { value: "Construction", label: "Construction" },
  { value: "Consulting", label: "Consulting" },
  { value: "Education", label: "Education" },
  { value: "Electronics", label: "Electronics" },
  { value: "Energy", label: "Energy" },
  { value: "Engineering", label: "Engineering" },
  { value: "Entertainment", label: "Entertainment" },
  { value: "Environmental", label: "Environmental" },
  { value: "Financial Services", label: "Financial Services" },
  { value: "Food &amp; Beverage", label: "Food &amp; Beverage" },
  { value: "Government", label: "Government" },
  { value: "Healthcare", label: "Healthcare" },
  { value: "Healthcare Gov", label: "Healthcare Gov" },
  { value: "Healthcare LS", label: "Healthcare LS" },
  { value: "Healthcare Payers", label: "Healthcare Payers" },
  { value: "Healthcare Providers", label: "Healthcare Providers" },
  { value: "Household chemicals", label: "Household chemicals" },
  { value: "Hospitality", label: "Hospitality" },
  { value: "Industrial Chemicals", label: "Industrial Chemicals" },
  { value: "Insurance", label: "Insurance" },
  { value: "Legal", label: "Legal" },
  { value: "Machinery", label: "Machinery" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Media", label: "Media" },
  { value: "Recreation", label: "Recreation" },
  { value: "Retail", label: "Retail" },
  { value: "Not for Profit", label: "Not for Profit" },
  { value: "Pharmaceuticals", label: "Pharmaceuticals" },
  {
    value: "Staffing &amp; Recruiting services",
    label: "Staffing &amp; Recruiting services",
  },
  { value: "Public Sector", label: "Public Sector" },
  {
    value: "Staffing and Recruiting Services",
    label: "Staffing and Recruiting Services",
  },
  { value: "Technology", label: "Technology" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Transportation", label: "Transportation" },
  { value: "Utilities", label: "Utilities" },
  { value: "Other", label: "Other" },
];
